---
name: Build Aviary Linux
on:
  pull_request:
    branches:
      - main
  #schedule:
  #  - cron: '05 10 * * *'  # 10:05am UTC everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '/lint.sh'

  workflow_dispatch:
concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true
jobs:
  bluebuild:
    name: Build Aviary Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            base-recipe:
              - 'recipes/base-recipe.yml'
      - name: Build Aviary Base Image
        uses: blue-build/github-action@v1.11
        if: steps.filter.outputs.base-recipe == 'true'
        with:
          cli_version:  v0.9.26
          recipe: base-recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          use_cache: true
          rechunk: true

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true

          skip_checkout: true

      - name: Build Aviary Image
        uses: blue-build/github-action@v1.11
        with:
          cli_version:  v0.9.26
          recipe: recipe.yml
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}

          # enabled by default, disable if your image is small and you want faster builds
          maximize_build_space: true

          skip_checkout: true
